repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json

-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: local
    hooks:
      - id: check-commit-message
        name: Commit message check
        entry: |
          bash -c "COMMIT_MSG=$(cat $1); 
                   if ! echo \"$COMMIT_MSG\" | grep -E '^(feat|fix|update|docs|chore|refactor|test|style): '; 
                   then echo 'Invalid commit message. Use format: feat/fix/etc: Message'; 
                   exit 1; 
                   fi"
        language: system
